### ISSUE TITLE
OSError on phold install

### ISSUE THREAD

**Issue by jonbakerlab** [gbouras13/phold#40]
* phold version: 0.1.4
* Python version: 3.10.14
* Operating System: GNU/Linux

### Description

I'm getting an error when trying to install the database on our server.  phold was installed using `$ mamba create -n phold_env -c conda-forge -c bioconda phold`, activated the environment and ran `phold install`.  Any help would be greatly appreciated, thanks for a great suite of tools!

### What I Did

```
$ phold install
2024-05-17 12:15:44.241 | INFO     | phold:install:1097 - Downloading the Phold database into the default directory /home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/phold/database
2024-05-17 12:15:44.242 | INFO     | phold:install:1104 - Checking that the Rostlab/ProstT5_fp16 ProstT5 model is available in /home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/phold/database
2024-05-17 12:15:44.242 | INFO     | phold.features.predict_3Di:get_T5_model:121 - Using device: cpu
2024-05-17 12:15:44.242 | INFO     | phold.features.predict_3Di:get_T5_model:127 - Loading T5 from: /home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/phold/database/Rostlab/ProstT5_fp16
2024-05-17 12:15:44.243 | INFO     | phold.features.predict_3Di:get_T5_model:128 - If /home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/phold/database/Rostlab/ProstT5_fp16 is not found, it will be downloaded
/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 733/733 [00:00<00:00, 5.21MB/s]
Traceback (most recent call last):
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/bin/phold", line 10, in <module>
    sys.exit(main())
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/phold/__init__.py", line 1355, in main
    main_cli()
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/phold/__init__.py", line 1112, in install
    model, vocab = get_T5_model(database, model_name, cpu)
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/phold/features/predict_3Di.py", line 129, in get_T5_model
    model = T5EncoderModel.from_pretrained(model_name, cache_dir=f"{model_dir}/").to(
  File "/home/exacloud/gscratch/BakerLab/miniforge3/envs/phold_env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3406, in from_pretrained
    raise EnvironmentError(
OSError: Rostlab/ProstT5_fp16 does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
```

**Comment by gbouras13** [comment]
Hi @jonbakerlab ,

Thanks for the kind words mate. With this error, I can't replicate it, so my suspicion is that either it is a Hugging Face related issue - sometimes the site can go down temporarily, or something relating to your machine. Perhaps try again, and if the error persists let me know!

George

**Comment by lzk98** [comment]
Most likely because of network restrictions in my area for some reason. Whether you can provide a link to download the database in other storage forms.

**Comment by gbouras13** [comment]
Hi @lzk98,

I do know HuggingFace (where ProstT5 lives) is restricted in China. So I think a backup option as you say would be a good idea. I'll do that and let you know how it goes.

George

**Comment by jonbakerlab** [comment]
Tried it again today and it worked...weird.  Thanks for your reply!

**Comment by gbouras13** [comment]
Awesome @jonbakerlab ,

@lzk98, if you have Hugging Face issues, you can download the model from Zenodo here https://zenodo.org/records/11234657

You will then need to untar the tarball (`tar -xzf models--Rostlab--ProstT5_fp16.tar.gz`) in the desired database directory for phold. I'll write some code to make this automatic for the next version release but it should work for now.

George
