### ISSUE TITLE
KeyError when analyzing pharokka output

### ISSUE THREAD

**Issue by mesti90** [gbouras13/phold#41]
* phold version: 0.1.4
* Python version: 3.11.4
* Operating System: ubuntu 23.04

### Description

I tried to run phold run on a genbank which was an output of pharokka.
The program crashed with the traceback shown below.

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

The command I ran:

`phold run -d phold_db -i pharokka.gbk --cpu --force --threads 50`

The error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/phold", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/phold/__init__.py", line 1355, in main
    main_cli()
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/phold/__init__.py", line 298, in run
    subcommand_compare(
  File "/usr/local/lib/python3.11/dist-packages/phold/subcommands/compare.py", line 129, in subcommand_compare
    non_cds_feature.qualifiers["ID"][0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'ID'


```

**Edit:**

I also tried running phold 0.1.5 (the dev version referred to in https://github.com/gbouras13/phold/issues/31), but it wasn't successful

**Comment by gbouras13** [comment]
Hi @mesti90 ,

How big is the Genbank? Do you mind sending it to me (George.bouras@adelaide.edu.au). I'm pretty sure this is because your phage(s) have a CRISPR repeat or tmRNA that is breaking phold, so I'll add some support for this and push it to the dev branch.

I will be on holidays the rest of this month but sometime in July an improved release will be available.

George
