### ISSUE TITLE
Phold crashes when the start position is 0

### ISSUE THREAD

**Issue by konstytucja** [gbouras13/phold#49]
* phold version:0.1.4
* Python version:3.10.14
* Operating System: Debian GNU/Linux 10

### Description

There is a problem when in the input file the start position is equal to 0. The tool starts but eventually fails at the Foldseek output processing. I think this is Biopython problem.

```
2024-07-11 08:17:06.648 | INFO     | phold.utils.validation:instantiate_dirs:70 - Checking the output directory cdiff_phage


.______    __    __    ______    __       _______  
|   _  \  |  |  |  |  /  __  \  |  |     |       \ 
|  |_)  | |  |__|  | |  |  |  | |  |     |  .--.  |
|   ___/  |   __   | |  |  |  | |  |     |  |  |  |
|  |      |  |  |  | |  `--'  | |  `----.|  '--'  |
| _|      |__|  |__|  \______/  |_______||_______/ 
                                                   


2024-07-11 08:17:06.662 | INFO     | phold.utils.util:begin_phold:72 - phold: annotating phage genomes with protein structures
2024-07-11 08:17:06.663 | INFO     | phold.utils.util:begin_phold:74 - You are using phold version 0.1.4
2024-07-11 08:17:06.663 | INFO     | phold.utils.util:begin_phold:75 - Repository homepage is https://github.com/gbouras13/phold
2024-07-11 08:17:06.663 | INFO     | phold.utils.util:begin_phold:76 - You are running phold run
2024-07-11 08:17:06.663 | INFO     | phold.utils.util:begin_phold:77 - Listing parameters
2024-07-11 08:17:06.663 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --input pharokka.gbk
2024-07-11 08:17:06.664 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --output cdiff_phage
2024-07-11 08:17:06.664 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --threads 16
2024-07-11 08:17:06.664 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --force False
2024-07-11 08:17:06.664 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --prefix phold
2024-07-11 08:17:06.664 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --evalue 0.001
2024-07-11 08:17:06.664 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --database phold
2024-07-11 08:17:06.665 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --batch_size 1
2024-07-11 08:17:06.665 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --sensitivity 9.5
2024-07-11 08:17:06.665 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --keep_tmp_files False
2024-07-11 08:17:06.665 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --cpu True
2024-07-11 08:17:06.665 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --omit_probs False
2024-07-11 08:17:06.666 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --finetune False
2024-07-11 08:17:06.666 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --finetune_path None
2024-07-11 08:17:06.666 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --split False
2024-07-11 08:17:06.666 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --split_threshold 60.0
2024-07-11 08:17:06.666 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --card_vfdb_evalue 1e-10
2024-07-11 08:17:06.666 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --separate False
2024-07-11 08:17:06.667 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --max_seqs 1000
2024-07-11 08:17:06.693 | INFO     | phold.utils.validation:check_dependencies:117 - Foldseek version found is v8.ef4e960
2024-07-11 08:17:06.694 | INFO     | phold.utils.validation:check_dependencies:126 - Foldseek version is ok
2024-07-11 08:17:06.694 | INFO     | phold.databases.db:validate_db:234 - Checking Phold database installation in phold
2024-07-11 08:17:06.696 | INFO     | phold.databases.db:validate_db:237 - All Phold databases files are present
2024-07-11 08:17:06.697 | INFO     | phold.io.handle_genbank:get_genbank:57 - Checking if input pharokka.gbk is a Genbank file
/opt/conda/lib/python3.10/site-packages/Bio/GenBank/__init__.py:727: BiopythonParserWarning: negative starting position in feature location '0..1407'; setting feature location to None.
  warnings.warn(
2024-07-11 08:17:06.724 | INFO     | phold.utils.validation:validate_input:50 - Successfully parsed input pharokka.gbk as a Genbank format file
2024-07-11 08:17:06.725 | INFO     | phold.features.predict_3Di:get_T5_model:121 - Using device: cpu
2024-07-11 08:17:06.725 | INFO     | phold.features.predict_3Di:get_T5_model:127 - Loading T5 from: phold/Rostlab/ProstT5_fp16
2024-07-11 08:17:06.726 | INFO     | phold.features.predict_3Di:get_T5_model:128 - If phold/Rostlab/ProstT5_fp16 is not found, it will be downloaded
/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-07-11 08:17:33.133 | INFO     | phold.features.predict_3Di:get_T5_model:138 - Rostlab/ProstT5_fp16 loaded
2024-07-11 08:17:33.151 | INFO     | phold.features.predict_3Di:get_embeddings:362 - Beginning ProstT5 predictions
2024-07-11 08:17:33.151 | INFO     | phold.features.predict_3Di:get_embeddings:369 - Using models in full-precision
2024-07-11 08:44:33.682 | INFO     | phold.features.predict_3Di:write_predictions:218 - Finished writing results to cdiff_phage/phold_3di.fasta
2024-07-11 08:44:33.751 | INFO     | phold.utils.external_tools:run:44 - Started running foldseek tsv2db cdiff_phage/foldseek_db/aa.tsv cdiff_phage/foldseek_db/phold --output-dbtype 0 ...
2024-07-11 08:44:33.761 | INFO     | phold.utils.external_tools:run:46 - Done running foldseek tsv2db cdiff_phage/foldseek_db/aa.tsv cdiff_phage/foldseek_db/phold --output-dbtype 0
2024-07-11 08:44:33.763 | INFO     | phold.utils.external_tools:run:44 - Started running foldseek tsv2db cdiff_phage/foldseek_db/3di.tsv cdiff_phage/foldseek_db/phold_ss --output-dbtype 0 ...
2024-07-11 08:44:33.769 | INFO     | phold.utils.external_tools:run:46 - Done running foldseek tsv2db cdiff_phage/foldseek_db/3di.tsv cdiff_phage/foldseek_db/phold_ss --output-dbtype 0
2024-07-11 08:44:33.770 | INFO     | phold.utils.external_tools:run:44 - Started running foldseek tsv2db cdiff_phage/foldseek_db/header.tsv cdiff_phage/foldseek_db/phold_h --output-dbtype 12 ...
2024-07-11 08:44:33.776 | INFO     | phold.utils.external_tools:run:46 - Done running foldseek tsv2db cdiff_phage/foldseek_db/header.tsv cdiff_phage/foldseek_db/phold_h --output-dbtype 12
2024-07-11 08:44:33.790 | INFO     | phold.utils.external_tools:run:44 - Started running foldseek search cdiff_phage/foldseek_db/phold phold/all_phold_structures cdiff_phage/result_db/result_db cdiff_phage/temp_db --threads 16 -e 0.001 -s 9.5 --max-seqs 1000 ...
2024-07-11 08:44:51.323 | INFO     | phold.utils.external_tools:run:46 - Done running foldseek search cdiff_phage/foldseek_db/phold phold/all_phold_structures cdiff_phage/result_db/result_db cdiff_phage/temp_db --threads 16 -e 0.001 -s 9.5 --max-seqs 1000
2024-07-11 08:44:51.324 | INFO     | phold.utils.external_tools:run:44 - Started running foldseek createtsv cdiff_phage/foldseek_db/phold phold/all_phold_structures cdiff_phage/result_db/result_db cdiff_phage/foldseek_results.tsv ...
2024-07-11 08:44:51.720 | INFO     | phold.utils.external_tools:run:46 - Done running foldseek createtsv cdiff_phage/foldseek_db/phold phold/all_phold_structures cdiff_phage/result_db/result_db cdiff_phage/foldseek_results.tsv
2024-07-11 08:44:51.721 | INFO     | phold.results.topfunction:get_topfunctions:35 - Processing Foldseek output
Traceback (most recent call last):
  File "/opt/conda/bin/phold", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/phold/__init__.py", line 1355, in main
    main_cli()
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/phold/__init__.py", line 298, in run
    subcommand_compare(
  File "/opt/conda/lib/python3.10/site-packages/phold/subcommands/compare.py", line 382, in subcommand_compare
    per_cds_df = write_genbank(
  File "/opt/conda/lib/python3.10/site-packages/phold/io/handle_genbank.py", line 227, in write_genbank
    sorted_features = sorted(all_features, key=lambda x: x.location.start)
  File "/opt/conda/lib/python3.10/site-packages/phold/io/handle_genbank.py", line 227, in <lambda>
    sorted_features = sorted(all_features, key=lambda x: x.location.start)
AttributeError: 'NoneType' object has no attribute 'start'
```

Are you able to fix that as Pharokka starts counting from 0 and it happens from time to time?

### How to recreate

You can run Pharokka and Phold on this genome: [https://www.ncbi.nlm.nih.gov/nuccore/MW512570.1/ ](MW512570)

**Comment by gbouras13** [comment]
Hi @konstytucja ,

Can you upload the pharokka output you are using (and the version)? I have a feeling you may be using some output a very old version of Pharokka.

Your error seems to be from this which suggests the first CDS is labelled as starting from 0. 

```
/opt/conda/lib/python3.10/site-packages/Bio/GenBank/__init__.py:727: BiopythonParserWarning: negative starting position in feature location '0..1407'; setting feature location to None.
  warnings.warn(
```

The Genbank format is 1-indexed so this shouldn't happen, but I suspect this was potentially an issue in an early version of pharokka.

With the latest version (v1.7.3), Pharokka starts counting at 1 - I've uploaded the genbank.

[pharokka.gbk.txt](https://github.com/user-attachments/files/16184842/pharokka.gbk.txt)


George

**Comment by konstytucja** [comment]
I was using 1.7.0 version of Pharokka and after upgrading everything works like a charm! Thank you for help!
