### ISSUE TITLE
phold run error 

### ISSUE THREAD

**Issue by ChaoXianSen** [gbouras13/phold#56]
* phold version:    version 0.2.0
* Python version:  Python 3.11.9
* Operating System:   Linux sil1c4u26-admin7 3.10.0-957.el7.x86_64

### Description
phold run -i ./pharokka_output/pharokka.gbk -o phold_output -t 8

I am trying to run phold on the output of pharokka, I get the following error:

Traceback (most recent call last):
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Rostlab/ProstT5_fp16/resolve/main/tokenizer_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/bin/phold", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/phold/__init__.py", line 1382, in main
    main_cli()
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/phold/__init__.py", line 293, in run
    subcommand_predict(
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/phold/subcommands/predict.py", line 161, in subcommand_predict
    prediction_success = get_embeddings(
                         ^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/phold/features/predict_3Di.py", line 433, in get_embeddings
    model, vocab = get_T5_model(model_dir, model_name, cpu)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/phold/features/predict_3Di.py", line 160, in get_T5_model
    vocab = T5Tokenizer.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/transformers/utils/hub.py", line 399, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1282, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/pholdENV/lib/python3.11/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Rostlab/ProstT5_fp16/resolve/main/tokenizer_config.json(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))"), '(Request ID: bbcb5bf5-4179-4e8a-865b-176873fdf84c)')

Where is is an error in the run?

Looking forward to your reply!

**Comment by gbouras13** [comment]
Hi @ChaoXianSen ,

This is probably a hugging face blocked in China (looks like you are in China from your account!) issue.

Pholddb should be installable without hugging face thanks to the mirror for ProstT5 I uploaded on zenodo.

Try adding `TRANSFORMERS_OFFLINE=True` before running phold.

George
