### ISSUE TITLE
phold.features.predict_3Di:get_embeddings:592 - prediction has length 0

### ISSUE THREAD

**Issue by mikenada** [gbouras13/phold#74]
* phold version: 0.2.0
* Python version: 3.12.2
* Operating System: Linux 

### Description

I am running phold run on one phage genome. The .gbk file is generated from pharokka and phold return an error of "TypeError: len() of unsized object"

### What I Did
 phold run -i pharokka_VIPKPNMC05/VIPKPNMC05.gbk --cpu -o phold_VIPKPNMC05 -t 10 -p VIPKPNMC05

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

2024-10-14 10:10:33.325 | INFO     | phold.utils.validation:instantiate_dirs:70 - Checking the output directory phold_VIPKPNMC05


.______    __    __    ______    __       _______
|   _  \  |  |  |  |  /  __  \  |  |     |       \
|  |_)  | |  |__|  | |  |  |  | |  |     |  .--.  |
|   ___/  |   __   | |  |  |  | |  |     |  |  |  |
|  |      |  |  |  | |  `--'  | |  `----.|  '--'  |
| _|      |__|  |__|  \______/  |_______||_______/



2024-10-14 10:10:33.338 | INFO     | phold.utils.util:begin_phold:72 - phold: annotating phage genomes with protein structures
2024-10-14 10:10:33.339 | INFO     | phold.utils.util:begin_phold:74 - You are using phold version 0.2.0
2024-10-14 10:10:33.339 | INFO     | phold.utils.util:begin_phold:75 - Repository homepage is https://github.com/gbouras13/phold
2024-10-14 10:10:33.340 | INFO     | phold.utils.util:begin_phold:76 - You are running phold run
2024-10-14 10:10:33.340 | INFO     | phold.utils.util:begin_phold:77 - Listing parameters
2024-10-14 10:10:33.340 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --input pharokka_VIPKPNMC05/VIPKPNMC05.gbk
2024-10-14 10:10:33.340 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --output phold_VIPKPNMC05
2024-10-14 10:10:33.341 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --threads 10
2024-10-14 10:10:33.342 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --force False
2024-10-14 10:10:33.342 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --prefix VIPKPNMC05
2024-10-14 10:10:33.342 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --evalue 0.001
2024-10-14 10:10:33.343 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --database None
2024-10-14 10:10:33.343 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --batch_size 1
2024-10-14 10:10:33.343 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --sensitivity 9.5
2024-10-14 10:10:33.343 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --keep_tmp_files False
2024-10-14 10:10:33.344 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --cpu True
2024-10-14 10:10:33.344 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --omit_probs False
2024-10-14 10:10:33.344 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --finetune False
2024-10-14 10:10:33.344 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --finetune_path None
2024-10-14 10:10:33.344 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --card_vfdb_evalue 1e-10
2024-10-14 10:10:33.345 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --separate False
2024-10-14 10:10:33.345 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --max_seqs 10000
2024-10-14 10:10:33.345 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --save_per_residue_embeddings False
2024-10-14 10:10:33.345 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --save_per_protein_embeddings False
2024-10-14 10:10:33.346 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --only_representatives False
2024-10-14 10:10:33.346 | INFO     | phold.utils.util:begin_phold:79 - Parameter: --ultra_sensitive False
2024-10-14 10:10:33.359 | INFO     | phold.utils.validation:check_dependencies:126 - Foldseek version found is v9.427df8a
2024-10-14 10:10:33.360 | INFO     | phold.utils.validation:check_dependencies:135 - Foldseek version is ok
2024-10-14 10:10:33.360 | INFO     | phold.databases.db:validate_db:361 - Checking Phold database installation in /home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/database
2024-10-14 10:10:33.361 | INFO     | phold.databases.db:validate_db:364 - All Phold databases files are present
2024-10-14 10:10:33.361 | INFO     | phold.io.handle_genbank:get_genbank:57 - Checking if input pharokka_VIPKPNMC05/VIPKPNMC05.gbk is a Genbank file
2024-10-14 10:10:33.401 | INFO     | phold.utils.validation:validate_input:50 - Successfully parsed input pharokka_VIPKPNMC05/VIPKPNMC05.gbk as a Genbank format file
2024-10-14 10:10:33.404 | INFO     | phold.features.predict_3Di:get_T5_model:121 - Using device: cpu
2024-10-14 10:10:33.405 | INFO     | phold.features.predict_3Di:get_T5_model:127 - Loading T5 from: /home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/database/Rostlab/ProstT5_fp16
2024-10-14 10:10:33.405 | INFO     | phold.features.predict_3Di:get_T5_model:128 - If /home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/database/Rostlab/ProstT5_fp16 is not found, it will be downloaded
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
2024-10-14 10:10:45.390 | INFO     | phold.features.predict_3Di:get_T5_model:164 - Rostlab/ProstT5_fp16 loaded
/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/features/predict_3Di.py:366: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(checkpoint_path, map_location=device)
2024-10-14 10:10:45.429 | INFO     | phold.features.predict_3Di:get_embeddings:436 - Beginning ProstT5 predictions
2024-10-14 10:10:45.433 | INFO     | phold.features.predict_3Di:get_embeddings:443 - Using models in full-precision
2024-10-14 10:12:46.174 | WARNING  | phold.features.predict_3Di:get_embeddings:592 - VIPKPNMC05_CDS_0028 Klebsiella prediction has length 0
2024-10-14 10:13:27.471 | WARNING  | phold.features.predict_3Di:get_embeddings:592 - VIPKPNMC05_CDS_0052 Klebsiella prediction has length 0
2024-10-14 10:13:28.219 | WARNING  | phold.features.predict_3Di:get_embeddings:592 - VIPKPNMC05_CDS_0054 Klebsiella prediction has length 0
Traceback (most recent call last):
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/bin/phold", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/__init__.py", line 1382, in main
    main_cli()
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/__init__.py", line 293, in run
    subcommand_predict(
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/subcommands/predict.py", line 161, in subcommand_predict
    prediction_success = get_embeddings(
                         ^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/features/predict_3Di.py", line 625, in get_embeddings
    write_predictions(predictions, output_3di, proteins_flag)
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/features/predict_3Di.py", line 242, in write_predictions
    prediction_contig_dict = {
                             ^
  File "/home/dostvip2/miniconda3_v2/envs/pholdENV/lib/python3.11/site-packages/phold/features/predict_3Di.py", line 243, in <dictcomp>
    k: v for k, v in prediction_contig_dict.items() if len(v[0]) > 0
                                                       ^^^^^^^^^
TypeError: len() of unsized object
```

**Comment by gbouras13** [comment]
Hi @mikenada 

can you check these CDS? They are likely errors in the input genbank file and are erroneous cds calls.

see #47

if you made these with pharokka, please let me know.

george

**Comment by mikenada** [comment]
Hello @gbouras13  The genbank file was created using pharokka. I was able to run phold using the colab notebook and compare the results between pharokka (locally installed) and phold (colab) and there is not much difference except for the 10 additional hypothetical proteins annotated via phold. Hence, the genbank file might not be the problem? 

I still have several genomes that needs annotation hence,  I would still like to make the locally installed phold work. Any recomms will be appreciated. Thank you for the help!

**Comment by gbouras13** [comment]
@mikenada 

Can you check the CDS? Based on #47, I would assume they are tiny (e.g. 1 amino acid) which would mean that your local pharokka may be installed incorrectly. VIPKPNMC05_CDS_0028 VIPKPNMC05_CDS_0052 and VIPKPNMC05_CDS_0054 in particular

And certainly, let's fix the local install! I just think it is a pharokka installation issue not phold.

George

**Comment by mikenada** [comment]
Hello @gbouras13 Oh it seems to be issue. 

CDS             complement(21000..21629)
                     /ID="VIPKPNMC05_CDS_0028"
                     /transl_table=11
                     /phrog="No_PHROG"
                     /top_hit="No_PHROG"
                     /locus_tag="VIPKPNMC05_CDS_0028"
                     /function="unknown function"
                     /product="hypothetical protein"
                     /source="PHANOTATE_1.6.5"
                     /score="-30615.82"
                     /phase="0"
                     **/translation="Y"**

 CDS             complement(32201..32410)
                     /ID="VIPKPNMC05_CDS_0052"
                     /transl_table=11
                     /phrog="No_PHROG"
                     /top_hit="No_PHROG"
                     /locus_tag="VIPKPNMC05_CDS_0052"
                     /function="unknown function"
                     /product="hypothetical protein"
                     /source="PHANOTATE_1.6.5"
                     /score="-1.727606"
                     /phase="0"
                     **/translation="H"**

CDS             complement(33144..33245)
                     /ID="VIPKPNMC05_CDS_0054"
                     /transl_table=11
                     /phrog="No_PHROG"
                     /top_hit="No_PHROG"
                     /locus_tag="VIPKPNMC05_CDS_0054"
                     /function="unknown function"
                     /product="hypothetical protein"
                     /source="PHANOTATE_1.6.5"
                     /score="-0.102894"
                     /phase="0"
                     **/translation="N"**


Based on https://github.com/gbouras13/phold/issues/47, pharokka needs phanotate version=1.5.1, where I have  v1.6.5. Do you think downgrading the phanotate version to >=1.5.0,<1.6.4  would fix the issue?

**Comment by mikenada** [comment]
Hello Yes. I did pip install since the conda installation do not works for me. 

On the other note, i tried downgrading phanotate version through conda install -c bioconda phanotate=1.5.1. but got several issues. 

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides _python_rc needed by python-3.13.0rc2-h6355ac2_0_cp313t

Could not solve for environment specs
The following packages are incompatible
├─ phanotate 1.5.1**  is installable with the potential options
│  ├─ phanotate 1.5.1 would require
│  │  └─ matplotlib-base with the potential options
│  │     ├─ matplotlib-base [2.1.2|2.2.3|2.2.4|2.2.5] would require
│  │     │  └─ python >=2.7,<2.8.0a0 , which can be installed;
│  │     ├─ matplotlib-base [2.1.2|2.2.3|...|3.3.4] would require
│  │     │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  │     ├─ matplotlib-base [2.1.2|2.2.3|...|3.5.3] would require
│  │     │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  │     ├─ matplotlib-base [2.2.4|2.2.5|...|3.7.3] would require
│  │     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  │     ├─ matplotlib-base [2.2.5|3.3.2|...|3.9.2] would require
│  │     │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  │     ├─ matplotlib-base [3.4.3|3.5.0|...|3.9.2] would require
│  │     │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  │     ├─ matplotlib-base [3.6.1|3.6.2|...|3.9.2] would require
│  │     │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  │     ├─ matplotlib-base 3.8.0 would require
│  │     │  └─ pillow >=6.2.0  with the potential options
│  │     │     ├─ pillow [6.2.0|6.2.1] would require
│  │     │     │  └─ python >=2.7,<2.8.0a0 , which can be installed;
│  │     │     ├─ pillow [6.2.0|6.2.1|...|8.3.2] would require
│  │     │     │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  │     │     ├─ pillow [6.2.0|6.2.1|...|9.2.0] would require
│  │     │     │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  │     │     ├─ pillow [10.0.0|10.0.1|...|9.5.0] would require
│  │     │     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  │     │     ├─ pillow [10.0.0|10.0.1|...|9.5.0] would require
│  │     │     │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  │     │     ├─ pillow [10.0.0|10.0.1|...|9.5.0] would require
│  │     │     │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  │     │     ├─ pillow [10.0.0|10.0.1|...|9.5.0] would require
│  │     │     │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  │     │     ├─ pillow [10.0.1|10.1.0|10.2.0|10.3.0|10.4.0] would require
│  │     │     │  └─ libtiff >=4.6.0,<4.8.0a0  but there are no viable options
│  │     │     │     ├─ libtiff 4.6.0 would require
│  │     │     │     │  └─ libdeflate >=1.20,<1.21.0a0 , which conflicts with any installable versions previously reported;
│  │     │     │     ├─ libtiff 4.6.0 would require
│  │     │     │     │  └─ libdeflate >=1.19,<1.20.0a0 , which conflicts with any installable versions previously reported;
│  │     │     │     ├─ libtiff [4.6.0|4.7.0] would require
│  │     │     │     │  └─ libdeflate >=1.21,<1.22.0a0 , which conflicts with any installable versions previously reported;
│  │     │     │     ├─ libtiff 4.6.0 would require
│  │     │     │     │  └─ libdeflate >=1.18,<1.19.0a0 , which conflicts with any installable versions previously reported;
│  │     │     │     └─ libtiff 4.7.0 would require
│  │     │     │        └─ libdeflate >=1.22,<1.23.0a0 , which conflicts with any installable versions previously reported;
│  │     │     ├─ pillow 10.4.0 would require
│  │     │     │  └─ python >=3.13.0rc2,<3.14.0a0  with the potential options
│  │     │     │     ├─ python 3.13.0, which can be installed;
│  │     │     │     └─ python [3.13.0rc2|3.13.0rc3] would require
│  │     │     │        └─ _python_rc, which does not exist (perhaps a missing channel);
│  │     │     ├─ pillow [10.0.1|10.2.0|...|9.4.0] conflicts with any installable versions previously reported;
│  │     │     └─ pillow [6.2.0|6.2.1|7.0.0|7.1.2|7.2.0] conflicts with any installable versions previously reported;
│  │     ├─ matplotlib-base [3.8.1|3.8.2|...|3.9.2] would require
│  │     │  └─ pillow >=8  with the potential options
│  │     │     ├─ pillow [6.2.0|6.2.1|...|8.3.2], which can be installed (as previously explained);
│  │     │     ├─ pillow [6.2.0|6.2.1|...|9.2.0], which can be installed (as previously explained);
│  │     │     ├─ pillow [10.0.0|10.0.1|...|9.5.0], which can be installed (as previously explained);
│  │     │     ├─ pillow [10.0.0|10.0.1|...|9.5.0], which can be installed (as previously explained);
│  │     │     ├─ pillow [10.0.0|10.0.1|...|9.5.0], which can be installed (as previously explained);
│  │     │     ├─ pillow [10.0.0|10.0.1|...|9.5.0], which can be installed (as previously explained);
│  │     │     ├─ pillow [10.0.1|10.1.0|10.2.0|10.3.0|10.4.0], which cannot be installed (as previously explained);
│  │     │     ├─ pillow 10.4.0, which can be installed (as previously explained);
│  │     │     └─ pillow [10.0.1|10.2.0|...|9.4.0] conflicts with any installable versions previously reported;
│  │     ├─ matplotlib-base 3.9.2 would require
│  │     │  └─ python >=3.13.0rc2,<3.14.0a0  with the potential options
│  │     │     ├─ python 3.13.0, which can be installed;
│  │     │     └─ python [3.13.0rc2|3.13.0rc3], which cannot be installed (as previously explained);
│  │     └─ matplotlib-base [3.1.2|3.1.3|...|3.9.2] conflicts with any installable versions previously reported;
│  └─ phanotate 1.5.1 would require
│     └─ python_abi 3.6.* *_cp36m, which requires
│        └─ python 3.6.* , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.

**Comment by gbouras13** [comment]
Looks like the new version of python 3.13 is causing some grief (of course)

can you try a conda install with a lower version of python for the whole env `conda install pharokka python==3.11` or you can try phanotate with pip into that env `pip install phanotate==1.5.1`

**Comment by mikenada** [comment]
Thank you for the suggestions. Will re-run pharokka and phold to see if everything works fine.

**Comment by mikenada** [comment]
pharokka and phold seems working fine now. Thank you very much.
